// frontend/src/presentation/components/input/input.vue
<template>
  <div :class="$style.inputWrap">
    <input
      ref="input"
      :value="modelValue"
      :type="type"
      :name="name"
      placeholder=" "
      readOnly
      @focus="handleFocus"
      @input="$emit('update:modelValue', $event.target.value)"
    >
    <label @click="focusInput">{{ placeholder }}</label>
    <span
      v-if="title"
      :class="$style.status"
      :title="title"
    >
      🔴
    </span>
    <span
      v-else
      :class="$style.status"
      :title="`${$props.name} válido`"
    >
      🟢
    </span>
  </div>
</template>

<script>
import { defineComponent } from 'vue'

export default defineComponent({
  props: {
    placeholder: {
      type: String,
      required: true
    },
    type: {
      type: String,
      required: true
    },
    name: {
      type: String,
      required: true
    },
    title: String,
    modelValue: {
      type: String,
      required: true
    }
  },
  emits: ['update:modelValue'],
  methods: {
    handleFocus (event) {
      event.target.readOnly = false
    },
    focusInput () {
      this.$refs.input.focus()
    }
  }
})
</script>

<style module lang="scss">
  @import './input-styles.scss';
</style>

// frontend/src/presentation/components/input/input.tsx
import React, { useContext, useRef } from 'react'
import Styles from './input-styles.scss'
import { FormContext } from '@/presentation/contexts'

type Props = React.DetailedHTMLProps<React.InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>

const Input: React.FC<Props> = (props: Props) => {
  const { state, setState } = useContext(FormContext)
  const inputRef = useRef<HTMLInputElement>()
  const error = state[`${props.name}Error`]

  return (
    <div className={Styles.inputWrap}>
      <input
        {...props}
        ref={inputRef}
        placeholder=" "
        readOnly
        onFocus={e => { e.target.readOnly = false }}
        onChange={e => { setState({ ...state, [e.target.name]: e.target.value }) }}
        data-testid={props.name}
      />
      <label onClick={() => { inputRef.current.focus() } } data-testid={`${props.name}-label`}>
        {props.placeholder}
      </label>
      <span
        data-testid={`${props.name}-status`}
        title={error || `${props.name} válido`}
        className={Styles.status}
      >
        {error ? '🔴' : '🟢'}
      </span>
    </div>
  )
}

export default Input
